### PR TITLE
Travis CI integrated

### LINKED ISSUE #14: Integrate Travis CI
**Describe the chore**
Integrate Travis CI

https://docs.travis-ci.com/user/languages/android/
https://medium.com/@harmittaa/travis-ci-android-example-357f6e632fc4

**Would you like to work on the issue?**
- [ ] Yes
- [x] No

### PR DESCRIPTION
**Pull request by ShivangiSingh17**
Fixed #14 
Changes: Added travis.yml file to the codebase.

### CODE REVIEW

**Comment by ShivangiSingh17** [comment]
Suggest changes if any.

**Comment by abhijitramesh** [comment]
@yashk2000 Can you run the Travis build with this config on you local repository and review this pr

**Comment by yashk2000** [comment]
@abhijitramesh sure :+1:

**Comment by yashk2000** [comment]
@ShivangiSingh17 the travis file should be named `.travis.yml`.

**Comment by vchrombie** [comment]
Thanks for the PR @ShivangiSingh17. :slightly_smiling_face: 

I did the changes and I am merging this. :tada: 
It will be activated after this merge.

**Comment by aswinshenoy** [comment]
@ShivangiSingh17, @vchrombie - Please parse yml files through [YAML Formatter](https://jsonformatter.org/yaml-formatter), the merged `.travisci.yml` had basic syntax issues. Please make sure it passes [YAML Lint](http://www.yamllint.com/) before committing further changes.

**Pull request merged**
