### PR TITLE
Inserted Screenshots into README.md file

### LINKED ISSUE #8: Add screenshots of the app to README.md
**Describe the chore**
Screenshots of the current UI of the app should be added to the README. They can continuously be updated when the UI is updated.

**Would you like to work on the issue?**

- [ ] Yes
- [X] No

### PR DESCRIPTION
**Pull request by athiranair2000**
Fixed #8

### CODE REVIEW

**Comment by vchrombie** [comment]
> Could you please insert more space in between the pictures?

@athiranair2000 
maybe you can use [immadisairaj/Quiz/](https://github.com/immadisairaj/Quiz/) README as reference. I have a raw link so that you can have a look. :point_down: 

https://raw.githubusercontent.com/immadisairaj/Quiz/development/README.md

**Comment by athiranair2000** [comment]
Thanks for the reference :+1: 
Please do review the changes that I have done.

**Comment by yashk2000** [comment]
> ReadAll Activity is updated please have a look and change it
> And also mention which activity that screenshot belongs to, it helps a lot

@Chromicle @athiranair2000 no need to mention which screenshot belongs to which activity.

**Comment by yashk2000** [comment]
@athiranair2000 please do change the `READ ALL` screenshot though.

**Comment by yashk2000** [comment]
@athiranair2000 please update the pull request ASAP.

**Comment by vchrombie** [comment]
Thanks, @athiranair2000. :smile:

**Pull request merged**
