### PR TITLE
chore: Update README.md

### LINKED ISSUE #60: Update screenshots in readme.
**Describe the chore**
UI has been changed a lot. Please update screenshots in readme.

**Would you like to work on the issue?** (Yes/No)
NO.

### PR DESCRIPTION
**Pull request by Chromicle**
Fixed #60 

### changes
updated readme.md with recent activities UI

### CODE REVIEW

**Comment by yashk2000** [comment]
@Chromicle make it `chore: Update .......`

**Comment by yashk2000** [comment]
@Chromicle do not edit existing comments. Write a new comment of your own while responding.

**Comment by Chromicle** [comment]
> @Chromicle, not 7 screenshots. Limit it to 6. Otherwise, there will be one extra screenshot in an entire row of its own which looks a bit weird.

Yeah, I also think about it I updated to 6 screenshots

**Comment by yashk2000** [comment]
Great. Just squash your commits please :)

**Pull request merged**
