### PR TITLE
fix: Dimensions edited

### LINKED ISSUE #102: Edit textbox dimension
**Describe the bug**
The size of the text box under Search ID and Delete Pooja/Donation should be changed for the watermark to appear.

### PR DESCRIPTION
**Pull request by ShivangiSingh17**
Fixed #102 

The dimensions are edited for the watermark to appear.

### CODE REVIEW

**Comment by immadisairaj** [comment]
@ShivangiSingh17 can you please resolve conflicts. And also would be better if screenshots are also added.

**Comment by yashk2000** [comment]
@ShivangiSingh17 please resolve conflicts.

**Comment by yashk2000** [comment]
@immadisairaj merge.

**Comment by vchrombie** [comment]
@ShivangiSingh17, thanks for the PR. :slightly_smiling_face: 
Merging it. :tada:

**Pull request merged**
