### PR TITLE
fix: a clear toast message

### LINKED ISSUE #90: Edit toast messages in Search section
**Describe the bug**
When user clicks on "people who registered "in search section, wrong toast is appearing as"Selected to register pooja". It is repeating with "People who Donated money".

**Expected behavior**
A clear toast message.

**Screenshots**
image
image

**Would you like to work on the issue?** (Yes/No)
No.

### PR DESCRIPTION
**Pull request by bharathspi**
Fixed #90 

Changes:
changed incorrect toast messages in search id section

### CODE REVIEW

**Comment by abhijitramesh** [comment]
@bharathspi please don't create multiple PR's for a single issue, you are suppose to fix the initial PR.

**Comment by yashk2000** [comment]
@bharathspi please update the pr with the requested changes soon. We can't wait this long for such a simple issue to be fixed.

**Comment by bharathspi** [comment]
@yashk2000 sry for the delay. I got some major issues with my laptop.So temporarily I cannot work on it. Meanwhile you can assign to someone else.

**Comment by yashk2000** [comment]
@bharathspi ok. I'm closing this pr therefore. If you want to work on it in the future, and the issue is still open, feel free to reopen the pr and continue the work.
Thanks for contributing :smile:

**Pull request closed without merging**
